const str = ` MrAjayNaranbhaiPatel
 KrishnaDairy
 PatelHarshil
 ZEPTOMARKETPLACEPRIVATELIMITED
 ROPPENTRANSPORTATIONSERVICESPRIVATELIMITED
 AirtelNCMC
 TARUNBHAIMANILALPRAJAPATI
 Maharajsandwich
 ARJUNPETROLEUM
 STARBAZAAR
 VadilalScoopShopKankubag
 STARBAZAAR
 KUSHWAHGAURISHANKAR
 BARIYASACHINKUMAR
 M/S.RATIONALHANDLOOMCOMPANYPRIVATELIMITED
 MAHESHSHIVAJITHAKOR
 KrishnaDairy
 Rapido
 PAPPUKUMAR
 RAMESHKUMARDEVAJIPRAJAPATI
 KrishnaDairy
 KrishnaDairy
 PrajapatiTarabenBharatbha
 KATHVADIYABHAVESHKUMAR
 Zomato
 KrishnaDairy
 Rapido
 AirtelNCMC
 AirtelNCMC
 PATILPRAVINDILIPBHAI
 VAISHALIBENDIPAKBHAICHAUHAN
 PURNIMAMOTORS
 Narpat Singh
 WESTSIDEUNITOFTRENTLIMITED
 AVENUESUPERMARTSLTD
 DIPIKABENJASVANTBHAIRATHOD
 PrajapatiTarabenBharatbha
 MSISHANIRAMESHBHAIPATEL
 KapilPatidar
 BadamiDevi
 NAGVADIYAAMRUTACHIRAGBHA
 MrVyas Gopal
 SBIcardsandPaymentservicesPvtLtd
 UtsavPandya
 RajShah
 GUJARATMETRORAILC
 SatishKumar
 CHAMUNDAGENERALSTORE
 GUJARATMETRORAILC
 BFTFRUITTRADERS
 ROPPENTRANSPORTATIONSERVICESPRIVATELIMITED
 Rajendrasingh
 Amul
 RAGHAVENDRAPUJARI
 AirtelNCMC
 AirtelNCMC
 KrishnaDairy
 Zomato
 VISHWAPROVISIONSTORE
 ARJUNPETROLEUM
 KAHARPRAKASHBHAIMILAN
 Rapido
 LALITBHAIRAMANBHAINAGAR
 SHREYAMEDICALSTORE
 HetalPrajapati
 SACHINBHAIBHAGAVANB
 KrishnaDairy
 PANCHALGEETABENBABALDAS
 MrHIMMATSIHBHERUSIHRATHOD
 BalajiPauvaHouse
 VishalTheUnisexSalon
 PrajapatiTarabenBharatbha
 AayushMedicalAndGeneralStores
 MukeshKumar
 GirirajVasanBhandar
 MAHENDRABHAIKANJIBHAIPATEL
 MrHIMMATSIHBHERUSIHRATHOD
 Adanigaslimited
 TEJASKUMARKANAIYALALTHAKKAR
 DASLIVEDHOKL
 Rana Priyeshkumar
 RAMESHKUMARDEVAJIPRAJAPATI
 ARJUNPETROLEUM
 DARSHANDEVELOPERS
 OSIAHYPERRETAILVASTRAL1
 PrajapatiTarabenBharatbha
 RAMESHKUMARDEVAJIPRAJAPATI
 BFTFURITTREDARS
 PATNI AJAYBHAI
 MrHIMMATSIHBHERUSIHRATHOD
 Zomato
 AirtelNCMC
 YamrajChidilalPariyar
 ARJUNPETROLEUM
 Rapido
 MrHIMMATSIHBHERUSIHRATHOD
 ROPPENTRANSPORTATIONSERVICESPRIVATELIMITED
 VISHWAPROVISIONSTORE
 NewKarnavatiFastFood
 BAJAJFINANCELTD`
const names = str.split('\n').map(s=>s.trim())

const isAllCaps = (s) => s === s.toUpperCase()

const result = []
let str2 = `
`

names.forEach((s) => {
  if (isAllCaps(s) || s.includes(' ')) {
    result.push(s)
str2+=s+'\n'
} else {
    const spaced = s.replace(/(?<=[a-z])[A-Z]/g, ' $&').trim()
    result.push(spaced)
str2+=spaced+'\n'
  
}
})

console.log(str2)